/* ══════════════ ATLAS — the four standing sheets ══════════════
   Plain data. Add your own sheets here to make them permanent;
   anything built through 'New subject' lives in Store instead.
   ══════════════════════════════════════════════════════════ */

/* ═══════════════ BUILT-IN SHEETS ═══════════════ */

const ECONOMICS = {
  id: "economics",
  name: "Economics",
  level: "Graduate / PhD qualifying-exam depth",
  blurb:
    "The body of theory a first-year doctoral student is expected to command before specialising. Field coverage is broad by design; genuine command of any two or three fields is what a dissertation is built on.",
  sections: [
    { title: "Mathematical & statistical foundations", note: "Without these the rest is memorised vocabulary.", topics: [
      ["Multivariable calculus", "partials, total differentials, implicit function theorem"],
      ["Constrained optimisation", "Lagrange, Kuhn–Tucker, envelope theorem"],
      ["Linear algebra", "eigenvalues, quadratic forms, definiteness"],
      ["Real analysis", "convexity, compactness, fixed-point theorems (Brouwer, Kakutani)"],
      ["Difference & differential equations", "phase diagrams, stability, saddle paths"],
      ["Dynamic optimisation", "optimal control, Hamiltonians, Bellman equations"],
      ["Probability theory", "distributions, LLN, central limit theorem"],
      ["Statistical inference", "MLE, method of moments, hypothesis testing"],
    ]},
    { title: "Consumer theory", note: "", topics: [
      ["Preference axioms & utility representation", "completeness, transitivity, continuity"],
      ["Marshallian & Hicksian demand", "the two demand systems and when each applies"],
      ["Indirect utility & expenditure functions", "Roy's identity, Shephard's lemma"],
      ["Slutsky equation", "income vs substitution decomposition"],
      ["Revealed preference", "WARP, SARP, recovering preferences from choice"],
      ["Welfare measurement", "compensating and equivalent variation, consumer surplus"],
      ["Intertemporal choice", "two-period model, borrowing constraints"],
      ["Labour–leisure choice", "reservation wage, backward-bending supply"],
    ]},
    { title: "Producer theory & market structure", note: "", topics: [
      ["Production functions & returns to scale", "isoquants, elasticity of substitution"],
      ["Cost minimisation and duality", "recovering technology from the cost function"],
      ["Short- vs long-run cost curves", "fixed factors, envelope of cost"],
      ["Perfect competition", "efficiency properties and their limits"],
      ["Monopoly & price discrimination", "first, second, third degree; deadweight loss"],
      ["Oligopoly", "Cournot, Bertrand, Stackelberg, collusion"],
      ["Monopolistic competition", "product differentiation, entry to zero profit"],
      ["Monopsony & contestable markets", "buyer power, hit-and-run entry"],
    ]},
    { title: "Game theory", note: "The common language of modern micro.", topics: [
      ["Normal & extensive form", "strategies vs actions, information sets"],
      ["Nash equilibrium", "existence, mixed strategies, refinements"],
      ["Subgame perfection", "backward induction, credible threats"],
      ["Repeated games", "folk theorems, trigger strategies, discounting"],
      ["Bayesian games & PBE", "types, beliefs, consistency"],
      ["Signalling & screening", "Spence, separating vs pooling equilibria"],
      ["Bargaining", "Nash solution, Rubinstein alternating offers"],
      ["Auction theory", "revenue equivalence, winner's curse, optimal auctions"],
      ["Mechanism design", "incentive compatibility, revelation principle, VCG"],
    ]},
    { title: "Uncertainty & information", note: "", topics: [
      ["Expected utility & its axioms", "von Neumann–Morgenstern, Allais paradox"],
      ["Risk aversion", "Arrow–Pratt measures, certainty equivalent"],
      ["Insurance & risk pooling", "optimal coverage, deductibles"],
      ["Adverse selection", "Akerlof lemons, market unravelling"],
      ["Moral hazard", "hidden action, effort incentives"],
      ["Principal–agent problems", "optimal contracts under risk and effort"],
      ["Contract theory", "incomplete contracts, hold-up, property rights"],
      ["Search & matching", "reservation strategies, frictional equilibrium"],
    ]},
    { title: "General equilibrium, welfare & market failure", note: "", topics: [
      ["Edgeworth box & the core", "exchange economies, contract curve"],
      ["Walrasian equilibrium", "existence, uniqueness, stability"],
      ["Two welfare theorems", "and precisely what assumptions they need"],
      ["Arrow's impossibility theorem", "aggregation of preferences"],
      ["Social welfare functions", "utilitarian, Rawlsian, Bergson–Samuelson"],
      ["Theory of the second best", "why partial fixes can hurt"],
      ["Externalities", "Pigouvian taxes, Coase theorem and its conditions"],
      ["Public goods & commons", "free riding, Samuelson condition, Lindahl pricing"],
    ]},
    { title: "Macro: accounting & the short run", note: "", topics: [
      ["National accounts", "three approaches, deflators, BoP, flow of funds"],
      ["Keynesian cross & multipliers", "and their empirical size"],
      ["IS–LM and AD–AS", "the workhorse teaching frames"],
      ["Mundell–Fleming", "open-economy policy under fixed vs floating rates"],
      ["Liquidity trap & zero lower bound", "when conventional policy stops working"],
      ["Automatic stabilisers", "cyclical vs structural balances"],
    ]},
    { title: "Money, inflation & monetary policy", note: "", topics: [
      ["Money creation & the central bank balance sheet", "multiplier vs endogenous money"],
      ["Quantity theory & money demand", "Baumol–Tobin, portfolio approaches"],
      ["Phillips curve", "original, expectations-augmented, NAIRU"],
      ["Costs of inflation", "menu, shoeleather, relative price distortion"],
      ["Hyperinflation & seigniorage", "fiscal roots of monetary collapse"],
      ["Policy rules", "Taylor rule, inflation targeting, nominal GDP targeting"],
      ["Time inconsistency", "Kydland–Prescott, central bank independence"],
      ["Unconventional policy", "QE, forward guidance, negative rates"],
    ]},
    { title: "Growth & the long run", note: "", topics: [
      ["Solow–Swan model", "steady state, golden rule, convergence"],
      ["Growth accounting", "TFP as a residual and what it hides"],
      ["Ramsey–Cass–Koopmans", "optimal saving, transversality"],
      ["Overlapping generations", "Diamond model, dynamic inefficiency"],
      ["Endogenous growth", "AK, Romer varieties, Aghion–Howitt creative destruction"],
      ["Human capital", "Lucas model, education and growth"],
      ["Institutions & growth", "property rights, extractive vs inclusive institutions"],
      ["Structural transformation", "agriculture to industry to services"],
    ]},
    { title: "Modern macro foundations", note: "Where the field actually operates.", topics: [
      ["Rational expectations & the Lucas critique", "why reduced forms break under policy change"],
      ["Real business cycle models", "technology shocks, calibration"],
      ["New Keynesian DSGE", "Calvo pricing, Euler equation, NK Phillips curve"],
      ["Consumption theory", "life-cycle, permanent income, random walk, precautionary saving"],
      ["Investment theory", "accelerator, Tobin's q, adjustment costs, irreversibility"],
      ["Labour search", "Diamond–Mortensen–Pissarides, Beveridge curve"],
      ["Heterogeneous agents", "HANK models, MPC distributions"],
      ["Fiscal policy & debt", "Ricardian equivalence, sustainability, multipliers"],
    ]},
    { title: "Open economy macro", note: "", topics: [
      ["Exchange rate regimes", "pegs, floats, currency boards"],
      ["Parity conditions", "PPP, covered and uncovered interest parity"],
      ["Current account dynamics", "intertemporal approach, sustainability"],
      ["Capital flows & sudden stops", "original sin, reserve accumulation"],
      ["Currency & sovereign debt crises", "first, second, third generation models"],
      ["Optimum currency areas", "Mundell criteria, euro area experience"],
      ["The impossible trinity", "and its modern dilemma variant"],
    ]},
    { title: "Econometrics", note: "", topics: [
      ["Classical linear regression", "OLS, Gauss–Markov, inference"],
      ["Violations & fixes", "heteroskedasticity, autocorrelation, robust/clustered SEs"],
      ["Endogeneity & instrumental variables", "2SLS, weak and many instruments, LATE"],
      ["Panel data", "fixed and random effects, dynamic panels, GMM"],
      ["Causal inference", "potential outcomes, RCTs, diff-in-diff, event studies"],
      ["Regression discontinuity & synthetic control", "design-based identification"],
      ["Matching & propensity scores", "selection on observables"],
      ["Limited dependent variables", "logit, probit, tobit, Heckman selection"],
      ["Time series", "stationarity, ARIMA, unit roots, cointegration, VARs"],
      ["Volatility & nonlinear models", "GARCH family, regime switching"],
      ["Estimation frameworks", "GMM, MLE, bootstrap, Bayesian methods"],
      ["Machine learning in econometrics", "lasso, causal forests, double ML"],
    ]},
    { title: "Applied fields", note: "Know all of them by shape; own two or three.", topics: [
      ["Public economics", "tax incidence, optimal taxation (Ramsey, Mirrlees), social insurance"],
      ["Labour economics", "human capital, wage structure, discrimination, minimum wage, migration"],
      ["International trade", "Ricardo, Heckscher–Ohlin, new trade theory, gravity, trade policy"],
      ["Development economics", "poverty and inequality measurement, RCTs, credit and insurance, informality"],
      ["Industrial organisation", "entry, differentiation, platforms, antitrust, regulation"],
      ["Behavioural economics", "prospect theory, present bias, social preferences, experiments"],
      ["Financial economics", "portfolio choice, asset pricing, market efficiency, crises"],
      ["Environmental economics", "carbon pricing, valuation, Hotelling, climate IAMs and discounting"],
      ["Health economics", "insurance markets, provider incentives, QALYs"],
      ["Urban & regional", "agglomeration, land use, housing, transport"],
      ["Political economy", "median voter, rent-seeking, institutions, voting theory"],
      ["Networks & matching markets", "diffusion, deferred acceptance, market design in practice"],
    ]},
    { title: "History, thought & methodology", note: "", topics: [
      ["Classical political economy", "Smith, Ricardo, Malthus, Mill, Marx"],
      ["Marginalist revolution", "Jevons, Menger, Walras, Marshall"],
      ["Keynes and the neoclassical synthesis", "General Theory and its reinterpretation"],
      ["Monetarism to new classical", "Friedman, Lucas, Sargent"],
      ["Heterodox critiques", "Austrian, post-Keynesian, institutionalist"],
      ["Economic history", "industrial revolution, Depression, Bretton Woods, 1970s, 2008, post-pandemic inflation"],
      ["Methodology", "positive vs normative, models as abstraction, identification"],
      ["Credibility & replication debates", "p-hacking, pre-registration, external validity"],
    ]},
  ],
};

const FINANCE = {
  id: "finance",
  name: "Finance",
  level: "Graduate / PhD qualifying-exam depth",
  blurb:
    "Asset pricing and corporate finance are the two theoretical pillars; stochastic calculus and empirical method are the tools that make them operational. Practice areas sit on top and change faster than the theory.",
  sections: [
    { title: "Mathematical foundations", note: "", topics: [
      ["Measure-theoretic probability", "probability spaces, filtrations, conditional expectation"],
      ["Stochastic processes", "Markov processes, martingales, stopping times"],
      ["Brownian motion & Itô calculus", "Itô's lemma, stochastic integrals, SDEs"],
      ["Change of measure", "Girsanov, Radon–Nikodym derivative, risk-neutral measure"],
      ["Jump processes", "Poisson and Lévy processes, jump-diffusion"],
      ["PDE methods", "Feynman–Kac, Black–Scholes PDE, boundary conditions"],
      ["Numerical methods", "binomial trees, finite differences, Monte Carlo, variance reduction"],
      ["Optimisation & dynamic programming", "portfolio problems in continuous and discrete time"],
    ]},
    { title: "Asset pricing theory", note: "", topics: [
      ["No arbitrage & law of one price", "the organising principle of the field"],
      ["Fundamental theorems of asset pricing", "equivalence of no arbitrage and a pricing measure"],
      ["Stochastic discount factor", "the single equation everything else specialises"],
      ["Complete vs incomplete markets", "spanning, replication, market frictions"],
      ["Mean-variance analysis", "efficient frontier, two-fund separation"],
      ["CAPM", "derivation, testable implications, Roll's critique"],
      ["APT & factor models", "Fama–French, Carhart, q-factor, factor zoo"],
      ["Consumption-based models", "CCAPM, equity premium and risk-free rate puzzles"],
      ["Habit, long-run risk, rare disasters", "the main resolutions and their costs"],
      ["Intertemporal & conditional models", "ICAPM, time-varying risk premia"],
      ["Return predictability", "dividend yield, term spread, out-of-sample debate"],
    ]},
    { title: "Derivatives & contingent claims", note: "", topics: [
      ["Forwards, futures, swaps", "cost of carry, basis, mark-to-market"],
      ["Option fundamentals", "payoffs, put–call parity, bounds"],
      ["Black–Scholes–Merton", "assumptions, derivation, replication argument"],
      ["The Greeks & hedging", "delta, gamma, vega, theta, rho, dynamic hedging"],
      ["Implied volatility", "smile, skew, term structure, volatility surface"],
      ["Local & stochastic volatility", "Dupire, Heston, SABR"],
      ["Jump and Lévy models", "Merton jump-diffusion, variance gamma"],
      ["American & exotic options", "early exercise, barriers, Asians, lookbacks"],
      ["Credit derivatives", "CDS pricing, CDO tranches, correlation"],
      ["Volatility products", "VIX, variance swaps, volatility risk premium"],
    ]},
    { title: "Fixed income & credit", note: "", topics: [
      ["Bond mathematics", "yield, duration, convexity, immunisation"],
      ["Yield curve construction", "bootstrapping, splines, discount factors"],
      ["Term structure theories", "expectations hypothesis, term premia, segmentation"],
      ["Short-rate models", "Vasicek, CIR, Hull–White, calibration"],
      ["Forward-rate & affine models", "HJM, LIBOR/SOFR market models"],
      ["Structural credit models", "Merton, distance to default, KMV"],
      ["Reduced-form credit models", "hazard rates, recovery, default correlation"],
      ["Securitisation", "MBS, prepayment risk, tranching, ABS"],
      ["Sovereign & municipal debt", "default risk, restructuring, ratings"],
    ]},
    { title: "Corporate finance", note: "", topics: [
      ["Capital budgeting", "NPV, IRR pitfalls, cash-flow estimation"],
      ["Cost of capital", "WACC, beta estimation, hurdle rates"],
      ["Modigliani–Miller", "with and without taxes; what the propositions really assume"],
      ["Capital structure theories", "trade-off, pecking order, market timing"],
      ["Financial distress & bankruptcy", "direct and indirect costs, Chapter 11 vs liquidation"],
      ["Payout policy", "dividends vs buybacks, signalling, clientele"],
      ["Agency theory", "manager–shareholder and shareholder–creditor conflicts"],
      ["Corporate governance", "boards, compensation, blockholders, activism"],
      ["Mergers & acquisitions", "synergies, method of payment, returns to acquirers"],
      ["Private equity & LBOs", "value creation, leverage, exits"],
      ["IPOs & security issuance", "underpricing, long-run performance, SEOs, SPACs"],
      ["Real options", "expansion, abandonment, timing under irreversibility"],
    ]},
    { title: "Market microstructure", note: "", topics: [
      ["Market designs", "quote-driven vs order-driven, auctions, dark pools"],
      ["Limit order books", "depth, resiliency, order types"],
      ["Spread decomposition", "order processing, inventory, adverse selection"],
      ["Kyle model", "informed trading, market depth, price informativeness"],
      ["Glosten–Milgrom", "sequential trade and learning"],
      ["Price discovery", "information shares, lead–lag across venues"],
      ["Liquidity measures", "Amihud, effective spread, Kyle's lambda"],
      ["High-frequency trading", "latency arbitrage, market making, flash events"],
      ["Execution & transaction costs", "implementation shortfall, optimal execution"],
    ]},
    { title: "Empirical finance", note: "", topics: [
      ["Event studies", "abnormal returns, estimation windows, inference"],
      ["Cross-sectional asset pricing tests", "Fama–MacBeth, GRS, errors in variables"],
      ["GMM tests of Euler equations", "Hansen–Jagannathan bounds and distance"],
      ["Portfolio sorts & factor construction", "breakpoints, weighting, robustness"],
      ["Anomalies and their fragility", "multiple testing, publication bias, decay"],
      ["Volatility estimation", "GARCH family, realised volatility, high-frequency data"],
      ["Predictive regressions", "Stambaugh bias, out-of-sample evaluation"],
      ["Machine learning in asset pricing", "return prediction, shrinkage, interpretation"],
    ]},
    { title: "Financial intermediation & institutions", note: "", topics: [
      ["Why banks exist", "delegated monitoring, maturity transformation"],
      ["Diamond–Dybvig", "runs, deposit insurance, multiple equilibria"],
      ["Capital & liquidity regulation", "Basel framework, leverage ratio, LCR/NSFR"],
      ["Money markets & repo", "collateral, haircuts, run dynamics"],
      ["Shadow banking", "money market funds, securitisation chains"],
      ["Central clearing & market infrastructure", "CCPs, margin, netting"],
      ["Systemic risk", "contagion, fire sales, funding spirals, macroprudential policy"],
      ["Financial crises", "history, anatomy, lender of last resort, resolution"],
    ]},
    { title: "Behavioural finance", note: "", topics: [
      ["Limits to arbitrage", "noise trader risk, funding constraints, horizon risk"],
      ["Investor biases", "overconfidence, disposition effect, attention, extrapolation"],
      ["Prospect theory applications", "loss aversion in asset pricing"],
      ["Sentiment", "measurement, cross-sectional effects"],
      ["Bubbles", "rational bubbles, herding, riding the bubble"],
      ["Household finance", "under-diversification, participation puzzles, financial literacy"],
    ]},
    { title: "Risk management", note: "", topics: [
      ["Value at Risk & expected shortfall", "estimation, backtesting, limitations"],
      ["Coherent risk measures", "axioms, subadditivity"],
      ["Dependence modelling", "correlation, copulas, tail dependence"],
      ["Stress testing & scenario analysis", "regulatory and internal frameworks"],
      ["Counterparty risk & XVA", "CVA, DVA, FVA, collateral"],
      ["Model risk", "validation, parameter uncertainty, misspecification"],
      ["Operational and liquidity risk", "measurement and controls"],
    ]},
    { title: "International & alternative markets", note: "", topics: [
      ["FX market structure", "spot, forwards, order flow"],
      ["Carry trade & forward premium puzzle", "the central FX anomaly"],
      ["International portfolio choice", "home bias, hedging currency exposure"],
      ["Commodities", "convenience yield, storage, futures curves"],
      ["Real estate", "valuation, REITs, illiquidity"],
      ["Private markets", "venture capital, PE returns measurement, J-curve"],
      ["Digital assets", "crypto market structure, stablecoins, DeFi mechanics"],
      ["ESG & sustainable finance", "screening, greenium, measurement problems"],
    ]},
    { title: "Portfolio management practice", note: "", topics: [
      ["Strategic vs tactical allocation", "policy portfolios, rebalancing"],
      ["Estimation error", "Black–Litterman, shrinkage, resampling"],
      ["Factor investing", "smart beta, crowding, capacity"],
      ["Performance evaluation", "Sharpe, information ratio, alpha attribution"],
      ["Benchmarking & tracking error", "active share, risk budgeting"],
      ["Liability-driven investing", "pensions, insurance ALM"],
      ["Taxes, costs and turnover", "after-tax and net-of-fee performance"],
    ]},
  ],
};

const MATHEMATICS = {
  id: "mathematics",
  name: "Mathematics",
  level: "Graduate / PhD qualifying-exam depth",
  blurb:
    "No one holds all of this at once. Qualifying exams typically cover algebra, analysis and topology or geometry; the rest is the landscape you should be able to orient yourself in and enter when a problem demands it.",
  sections: [
    { title: "Foundations & logic", note: "", topics: [
      ["Propositional & predicate logic", "syntax, semantics, completeness"],
      ["Set theory", "ZFC axioms, ordinals, cardinals, transfinite induction"],
      ["Axiom of choice", "equivalents (Zorn, well-ordering) and consequences"],
      ["Proof technique", "induction, contradiction, construction, diagonalisation"],
      ["Model theory", "compactness, Löwenheim–Skolem, elementary equivalence"],
      ["Computability", "Turing machines, recursive functions, undecidability"],
      ["Gödel's incompleteness theorems", "statement, proof sketch, misuse"],
      ["Category theory", "categories, functors, natural transformations, limits, adjunctions"],
    ]},
    { title: "Abstract algebra", note: "", topics: [
      ["Group theory", "actions, Sylow theorems, solvable and simple groups"],
      ["Representation theory", "characters, Maschke, Schur's lemma"],
      ["Ring theory", "ideals, quotients, PIDs, UFDs, Noetherian rings"],
      ["Modules", "structure theorem over PIDs, exact sequences"],
      ["Field theory & Galois theory", "extensions, solvability by radicals"],
      ["Commutative algebra", "localisation, Nakayama, primary decomposition, dimension"],
      ["Homological algebra", "chain complexes, derived functors, Ext and Tor"],
      ["Multilinear algebra", "tensor, symmetric and exterior algebras"],
    ]},
    { title: "Linear algebra & matrix analysis", note: "", topics: [
      ["Vector spaces & linear maps", "bases, dual spaces, quotients"],
      ["Canonical forms", "Jordan, rational, Smith normal form"],
      ["Inner product spaces", "orthogonality, adjoints, spectral theorem"],
      ["Matrix decompositions", "SVD, QR, LU, Cholesky, Schur"],
      ["Positive definiteness & quadratic forms", "Sylvester's law of inertia"],
      ["Perturbation & conditioning", "eigenvalue sensitivity, norms"],
    ]},
    { title: "Real analysis & measure theory", note: "", topics: [
      ["Metric & topological preliminaries", "completeness, compactness, connectedness"],
      ["Sequences, series & uniform convergence", "Arzelà–Ascoli, Stone–Weierstrass"],
      ["Differentiation in R^n", "inverse and implicit function theorems"],
      ["Lebesgue measure & integration", "construction, measurable functions"],
      ["Convergence theorems", "monotone, dominated, Fatou"],
      ["Lp spaces", "Hölder, Minkowski, completeness, duality"],
      ["Product measures", "Fubini–Tonelli"],
      ["Radon–Nikodym & differentiation of measures", "absolute continuity, Lebesgue decomposition"],
    ]},
    { title: "Complex analysis", note: "", topics: [
      ["Holomorphic functions", "Cauchy–Riemann, power series"],
      ["Cauchy theory", "integral theorem and formula, Liouville, maximum modulus"],
      ["Laurent series & residues", "singularity classification, contour integration"],
      ["Conformal mapping", "Möbius transformations, Schwarz lemma"],
      ["Riemann mapping theorem", "and normal families"],
      ["Analytic continuation", "monodromy, branch cuts"],
      ["Entire & meromorphic functions", "Weierstrass and Mittag-Leffler, Hadamard factorisation"],
      ["Riemann surfaces", "first concepts, uniformisation"],
    ]},
    { title: "Functional analysis", note: "", topics: [
      ["Banach & Hilbert spaces", "orthonormal bases, projections, Riesz representation"],
      ["The four pillars", "Hahn–Banach, open mapping, closed graph, uniform boundedness"],
      ["Dual spaces & weak topologies", "Banach–Alaoglu, reflexivity"],
      ["Compact operators", "Fredholm theory, spectral theory"],
      ["Spectral theorem", "bounded and unbounded self-adjoint operators"],
      ["Distributions", "test functions, weak derivatives, Fourier transform"],
      ["Sobolev spaces", "embeddings, trace, application to PDE"],
      ["Operator semigroups", "Hille–Yosida, evolution equations"],
    ]},
    { title: "Topology", note: "", topics: [
      ["Point-set topology", "separation axioms, compactness, Tychonoff, metrisation"],
      ["Fundamental group", "van Kampen, covering spaces, deck transformations"],
      ["Homology", "simplicial, singular, Mayer–Vietoris, excision"],
      ["Cohomology", "cup products, universal coefficients, de Rham"],
      ["Duality", "Poincaré, Alexander, Lefschetz fixed point"],
      ["Homotopy theory", "higher homotopy groups, fibrations, exact sequences"],
      ["Vector bundles & characteristic classes", "Chern and Stiefel–Whitney classes"],
    ]},
    { title: "Geometry", note: "", topics: [
      ["Smooth manifolds", "charts, tangent bundles, submersions, Sard"],
      ["Vector fields & flows", "Lie derivative, Frobenius theorem"],
      ["Differential forms", "exterior derivative, Stokes' theorem, de Rham cohomology"],
      ["Riemannian geometry", "metrics, connections, curvature, geodesics"],
      ["Comparison & global results", "Gauss–Bonnet, Hopf–Rinow, Bonnet–Myers"],
      ["Lie groups & Lie algebras", "exponential map, representations, classification"],
      ["Algebraic geometry", "affine and projective varieties, sheaves, schemes"],
      ["Complex & symplectic geometry", "Kähler manifolds, Hamiltonian systems"],
    ]},
    { title: "Differential equations & dynamics", note: "", topics: [
      ["ODE theory", "existence, uniqueness, continuous dependence"],
      ["Linear systems", "matrix exponentials, Floquet theory"],
      ["Stability", "Lyapunov functions, hyperbolicity, invariant manifolds"],
      ["Bifurcation theory", "saddle-node, Hopf, normal forms"],
      ["Chaos & ergodic theory", "attractors, Lyapunov exponents, mixing"],
      ["PDE classification", "elliptic, parabolic, hyperbolic; characteristics"],
      ["Classical equations", "Laplace, heat, wave; fundamental solutions, maximum principles"],
      ["Weak solutions & variational methods", "energy estimates, Lax–Milgram"],
      ["Nonlinear PDE", "conservation laws, shocks, viscosity solutions"],
    ]},
    { title: "Probability & stochastics", note: "", topics: [
      ["Measure-theoretic probability", "random variables, independence, conditional expectation"],
      ["Limit theorems", "LLN, CLT, characteristic functions, convergence modes"],
      ["Martingales", "optional stopping, convergence, Doob inequalities"],
      ["Markov chains", "classification, stationarity, mixing times"],
      ["Brownian motion", "construction, path properties, reflection principle"],
      ["Stochastic calculus", "Itô integral, SDEs, diffusion processes"],
      ["Large deviations", "Cramér, Sanov, rate functions"],
      ["Random matrices & concentration", "semicircle law, concentration inequalities"],
    ]},
    { title: "Number theory", note: "", topics: [
      ["Elementary number theory", "congruences, quadratic reciprocity, Diophantine equations"],
      ["Analytic number theory", "Dirichlet series, zeta function, prime number theorem"],
      ["Algebraic number theory", "number fields, rings of integers, class groups, units"],
      ["Local fields", "p-adic numbers, valuations, Hensel's lemma"],
      ["Elliptic curves", "group law, Mordell–Weil, torsion"],
      ["Modular forms", "Eisenstein series, Hecke operators, modularity"],
      ["Class field theory", "abelian extensions, reciprocity laws"],
    ]},
    { title: "Combinatorics & discrete mathematics", note: "", topics: [
      ["Enumeration", "generating functions, inclusion–exclusion, bijections"],
      ["Graph theory", "connectivity, colouring, planarity, matchings, spectral graph theory"],
      ["Extremal combinatorics", "Turán, Ramsey theory, Szemerédi regularity"],
      ["Probabilistic method", "first and second moment, Lovász local lemma"],
      ["Random graphs", "Erdős–Rényi thresholds, giant component"],
      ["Design theory & codes", "block designs, error-correcting codes"],
      ["Matroids & polyhedral combinatorics", "greedy, LP relaxations, total unimodularity"],
      ["Additive combinatorics", "sumsets, Freiman, Fourier methods"],
    ]},
    { title: "Optimisation & numerical analysis", note: "", topics: [
      ["Convex analysis", "convex sets and functions, subgradients, conjugates"],
      ["Linear programming & duality", "simplex, interior point, complementary slackness"],
      ["Nonlinear programming", "KKT conditions, penalty and barrier methods"],
      ["Integer & combinatorial optimisation", "branch and bound, cutting planes"],
      ["Stochastic & robust optimisation", "recourse, uncertainty sets"],
      ["Numerical linear algebra", "stability, conditioning, iterative solvers, Krylov methods"],
      ["Interpolation & quadrature", "splines, Gaussian quadrature, error bounds"],
      ["Numerical ODE/PDE", "Runge–Kutta, stiffness, finite difference, finite element, spectral methods"],
      ["Control theory", "state space, controllability, LQR, optimal control"],
    ]},
  ],
};

const COMPUTING = {
  id: "computing",
  name: "Computer Science",
  level: "Graduate / PhD qualifying-exam depth",
  blurb:
    "Theory, systems and intelligence are the three trunks. A doctoral student is expected to be fluent across all three at breadth level and to work at the frontier of one subarea.",
  sections: [
    { title: "Mathematical foundations", note: "", topics: [
      ["Discrete mathematics", "logic, sets, relations, induction, counting"],
      ["Graph theory for computing", "traversal, connectivity, spectral methods"],
      ["Probability & randomised analysis", "concentration bounds, Markov chains, coupling"],
      ["Linear algebra for computing", "SVD, projections, numerical stability"],
      ["Information theory", "entropy, mutual information, coding theorems, compression"],
      ["Formal logic", "propositional and first-order, SAT, satisfiability modulo theories"],
    ]},
    { title: "Algorithms", note: "", topics: [
      ["Asymptotic analysis & recurrences", "master theorem, amortised analysis"],
      ["Core paradigms", "divide and conquer, greedy, dynamic programming"],
      ["Graph algorithms", "shortest paths, spanning trees, SCCs, flows and matchings"],
      ["Advanced data structures", "balanced trees, heaps, union-find, tries, succinct structures"],
      ["Hashing & sketching", "universal hashing, Bloom filters, count-min, LSH"],
      ["Randomised algorithms", "Las Vegas vs Monte Carlo, random sampling"],
      ["Approximation algorithms", "LP rounding, primal-dual, greedy guarantees, hardness"],
      ["Online & streaming algorithms", "competitive ratio, sublinear space and time"],
      ["String algorithms", "suffix structures, pattern matching, alignment"],
      ["Computational geometry", "convex hulls, Voronoi, range searching"],
      ["Parallel & distributed algorithms", "PRAM, work-depth, MapReduce models"],
    ]},
    { title: "Theory of computation & complexity", note: "", topics: [
      ["Automata & formal languages", "regular, context-free, pushdown, Chomsky hierarchy"],
      ["Computability", "halting problem, reductions, Rice's theorem"],
      ["Complexity classes", "P, NP, coNP, PSPACE, EXP, BPP, #P, polynomial hierarchy"],
      ["NP-completeness", "Cook–Levin, standard reductions, practical implications"],
      ["Space complexity", "Savitch, NL-completeness, log-space reductions"],
      ["Randomness & derandomisation", "pseudorandom generators, expanders"],
      ["Interactive proofs & PCP", "IP=PSPACE, hardness of approximation"],
      ["Circuit complexity", "lower bounds, natural proofs barrier"],
      ["Quantum computation", "qubits, Shor, Grover, BQP, error correction"],
      ["Fine-grained complexity", "SETH, conditional lower bounds"],
    ]},
    { title: "Computer architecture", note: "", topics: [
      ["Instruction set architecture", "RISC vs CISC, ISA design tradeoffs"],
      ["Pipelining & hazards", "forwarding, branch prediction, speculation"],
      ["Instruction-level parallelism", "superscalar, out-of-order execution"],
      ["Memory hierarchy", "caches, associativity, prefetching, virtual memory hardware"],
      ["Multicore & coherence", "cache coherence protocols, memory consistency models"],
      ["Accelerators", "GPUs, SIMD, TPUs and systolic arrays, dataflow"],
      ["Performance modelling", "Amdahl, roofline, energy and thermal limits"],
      ["Reliability & security in hardware", "ECC, speculative execution vulnerabilities"],
    ]},
    { title: "Operating systems & runtime", note: "", topics: [
      ["Processes & threads", "scheduling, context switching, synchronisation primitives"],
      ["Concurrency", "locks, lock-free structures, deadlock, race conditions"],
      ["Virtual memory", "paging, TLB, page replacement, memory allocators"],
      ["File systems & storage", "journaling, log-structured design, SSD behaviour"],
      ["I/O and device management", "interrupts, DMA, async I/O"],
      ["Virtualisation & containers", "hypervisors, namespaces, cgroups"],
      ["Kernel design", "monolithic vs microkernel, system call interface"],
      ["Real-time & embedded systems", "scheduling guarantees, resource constraints"],
    ]},
    { title: "Programming languages & compilers", note: "", topics: [
      ["Lexing & parsing", "regular and context-free techniques, LL/LR"],
      ["Intermediate representations", "AST, SSA, control and data flow graphs"],
      ["Optimisation passes", "dataflow analysis, loop transforms, inlining, vectorisation"],
      ["Code generation", "register allocation, instruction selection and scheduling"],
      ["Runtime systems", "garbage collection, JIT compilation, calling conventions"],
      ["Type systems", "polymorphism, inference, subtyping, dependent and linear types"],
      ["Lambda calculus & semantics", "operational, denotational, axiomatic"],
      ["Paradigms", "functional, logic, object-oriented, array, dataflow"],
      ["Program analysis & verification", "abstract interpretation, model checking, Hoare logic"],
      ["Formal methods & proof assistants", "Coq, Lean, refinement, verified compilation"],
    ]},
    { title: "Networking & distributed systems", note: "", topics: [
      ["Protocol stack", "link, network, transport, application layers"],
      ["Routing", "intra- and inter-domain, BGP, SDN"],
      ["Transport & congestion control", "TCP variants, QUIC, fairness, bufferbloat"],
      ["Naming & content delivery", "DNS, CDNs, caching hierarchies"],
      ["Time, order & causality", "logical clocks, vector clocks, snapshots"],
      ["Consistency models", "linearisability, sequential, eventual, causal, CAP and PACELC"],
      ["Consensus", "Paxos, Raft, view-stamped replication, Byzantine fault tolerance"],
      ["Replication & partitioning", "quorums, sharding, rebalancing"],
      ["Distributed transactions", "two-phase commit, Spanner-style approaches, CRDTs"],
      ["Fault tolerance", "failure detectors, retries, idempotency, chaos testing"],
      ["Large-scale system design", "load balancing, queues, backpressure, capacity planning"],
      ["Blockchain & decentralised systems", "consensus under open membership, smart contracts"],
    ]},
    { title: "Databases & data systems", note: "", topics: [
      ["Relational model", "algebra, calculus, SQL semantics"],
      ["Schema design", "functional dependencies, normal forms, denormalisation tradeoffs"],
      ["Storage & indexing", "B-trees, LSM-trees, columnar layouts, compression"],
      ["Query processing & optimisation", "join algorithms, cardinality estimation, cost models"],
      ["Transactions", "ACID, isolation levels, serialisability theory"],
      ["Concurrency control", "2PL, MVCC, optimistic methods"],
      ["Recovery", "write-ahead logging, ARIES, checkpointing"],
      ["Distributed & NoSQL stores", "key-value, document, wide-column, graph databases"],
      ["Analytics & warehousing", "OLAP, star schemas, vectorised execution, lakehouse"],
      ["Stream processing", "windowing, watermarks, exactly-once semantics"],
      ["Data quality & governance", "lineage, schema evolution, privacy constraints"],
    ]},
    { title: "Artificial intelligence & machine learning", note: "", topics: [
      ["Search & planning", "heuristic search, constraint satisfaction, classical planning"],
      ["Knowledge representation & reasoning", "logic, ontologies, non-monotonic reasoning"],
      ["Probabilistic graphical models", "Bayesian networks, MRFs, inference, EM"],
      ["Statistical learning theory", "bias–variance, VC dimension, PAC learning, generalisation"],
      ["Supervised learning", "linear models, SVMs, trees, ensembles, boosting"],
      ["Unsupervised learning", "clustering, dimensionality reduction, density estimation"],
      ["Optimisation for learning", "SGD, momentum, adaptive methods, convergence"],
      ["Deep learning", "backpropagation, CNNs, RNNs, transformers, attention"],
      ["Training at scale", "initialisation, normalisation, regularisation, scaling laws, distributed training"],
      ["Generative models", "autoregressive models, VAEs, GANs, diffusion"],
      ["Reinforcement learning", "MDPs, value and policy methods, exploration, offline and deep RL"],
      ["Language & multimodal systems", "pretraining, fine-tuning, RLHF, retrieval, evaluation"],
      ["Computer vision", "detection, segmentation, 3D vision, representation learning"],
      ["Interpretability & robustness", "attribution, probing, adversarial examples, distribution shift"],
      ["Fairness, privacy & AI safety", "bias measurement, differential privacy, alignment, evaluation of risk"],
    ]},
    { title: "Security & cryptography", note: "", topics: [
      ["Threat modelling", "adversary models, trust boundaries, defence in depth"],
      ["Symmetric cryptography", "block ciphers, modes, MACs, hash functions"],
      ["Public-key cryptography", "RSA, discrete log, elliptic curves, key exchange"],
      ["Provable security", "reductions, random oracle model, security definitions"],
      ["Protocols", "TLS, authentication, PKI, key management"],
      ["Advanced cryptography", "zero-knowledge proofs, MPC, homomorphic encryption, commitments"],
      ["Systems security", "memory safety, exploitation, sandboxing, access control"],
      ["Network & web security", "injection, XSS, CSRF, DDoS, intrusion detection"],
      ["Side channels", "timing, cache, power analysis"],
      ["Privacy technology", "differential privacy, anonymity systems, secure enclaves"],
      ["Post-quantum cryptography", "lattice-based schemes and migration"],
    ]},
    { title: "Graphics, interaction & human factors", note: "", topics: [
      ["Rendering", "rasterisation, ray tracing, global illumination, BRDFs"],
      ["Geometry processing", "meshes, subdivision, parameterisation"],
      ["Animation & simulation", "rigging, physical simulation, fluids, collision"],
      ["GPU programming", "shaders, CUDA, memory models"],
      ["Interaction design", "affordances, mental models, input techniques"],
      ["Usability & evaluation", "controlled studies, qualitative methods, statistics for HCI"],
      ["Visualisation", "encoding channels, perception, interactive analytics"],
      ["Accessibility & inclusive design", "assistive technology, standards"],
      ["Computer-supported cooperative work", "collaboration systems, crowdsourcing"],
    ]},
    { title: "Software engineering & practice", note: "", topics: [
      ["Requirements & specification", "eliciting, modelling, tracing"],
      ["Architecture & design", "patterns, modularity, coupling and cohesion, API design"],
      ["Testing", "unit, integration, property-based, fuzzing, coverage"],
      ["Version control & collaboration", "branching models, code review"],
      ["Build, CI/CD & release engineering", "reproducibility, dependency management"],
      ["Observability & operations", "logging, metrics, tracing, incident response, SRE"],
      ["Refactoring & technical debt", "legacy code, migration strategies"],
      ["Process & teams", "agile methods, estimation, empirical software engineering"],
      ["Performance engineering", "profiling, benchmarking, optimisation discipline"],
      ["Systems for machine learning", "training infrastructure, serving, MLOps, compilers for ML"],
    ]},
  ],
};

const BUILT_IN = [ECONOMICS, FINANCE, MATHEMATICS, COMPUTING];

window.ATLAS_SHEETS = BUILT_IN;
